"""empty message

Revision ID: 273ce562c178
Revises: 
Create Date: 2026-01-06 18:39:23.286465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '273ce562c178'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_culture_type', sa.Integer(), nullable=True),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
