"""changes on the database(verification code and user info)

Revision ID: 7691c9a700d2
Revises: 273ce562c178
Create Date: 2026-01-07 08:28:49.571896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7691c9a700d2'
down_revision = '273ce562c178'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_culture_type', sa.Integer(), nullable=True),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('verificationCode',
    sa.Column('id_code', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_code'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificationCode')
    op.drop_table('user')
    # ### end Alembic commands ###
