"""initial

Revision ID: a23cdcf504b8
Revises: 8267a63a8621
Create Date: 2026-01-08 13:58:51.922285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23cdcf504b8'
down_revision = '8267a63a8621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('id_culture_type', sa.Integer(), nullable=True),
    sa.Column('farm_name', sa.String(length=200), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('mail'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('verificationCode',
    sa.Column('id_code', sa.Integer(), nullable=False),
    sa.Column('mail', sa.String(length=100), nullable=False),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.Column('checked', sa.Boolean(), nullable=False),
    sa.Column('expiry', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_code'),
    sa.UniqueConstraint('mail')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificationCode')
    op.drop_table('user')
    # ### end Alembic commands ###
